### ISSUE TITLE
Supported on MacOS 10.13?

### ISSUE THREAD

**Issue by Chem-Lab** [Kaviju/Html2PdfServer#3]
I did a test on my local machine (10.13.6) and I am having problems with the stability. One page documents are working, but larger documents don't work. I do prefer Html2PdfServer! It is a lot more stable and faster Than Wickedpdf.
Do you still support this, or what can I do to help?

Frank Stock

**Comment by spelletier** [comment]
I just tried some PDF on my dev machine and I experience crash during the PDF rendering in WebCore (part of WebView) when checking if an element has a css pageBreakInside value on the DOMHTMLDocument node. It is probably a recent problem.

I adjusted the code to skip this case. I will sent a new build soon.

**Comment by spelletier** [comment]
A new release is available with the fix.
